package com.coodev.module_compiler.util;

public class ModuleUtil {
    public static final String PROJECT = "ModuleBus";
    public static final String MODULE_UNIT = "ModuleUnit";
    public static final String INIT_PRE = "Init";
    public static final String SEPARATOR = "$$";

    public static final String FACADE_PACKAGE = "com.coodev.module_api";
    public static final String MODULE_ANNOTATION = "com.coodev.annotation";
    private static final String TEMPLATE_PACKAGE = ".template";
    public static final String NAME_OF_MODULEGROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY MODULEBUS.";


    public static final String IMODULE_GROUP = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IModuleGroup";
    public static final String IMODULE_UNIT = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".IModuleUnit";
    public static final String IINIT_UNIT = FACADE_PACKAGE + TEMPLATE_PACKAGE + ".Init";
    public static final String METHOD_LOAD_INTO = "loadInto";

    public static final String NAME_OF_MODULEUNIT = MODULE_UNIT + SEPARATOR;
    public static final String NAME_OF_INIT = INIT_PRE + SEPARATOR;

    public static final String ANNOTATION_TYPE_MODULEUNIT = MODULE_ANNOTATION + "ModuleUnit";

    public static final String ADDRESS_OF_MODULEUNIT = FACADE_PACKAGE + "." + MODULE_UNIT + SEPARATOR;
    public static final String ADDRESS_OF_INIT = FACADE_PACKAGE + "." + INIT_PRE + SEPARATOR;
}

